name: cool_devtool
description: "Flutter profiling, debugging & performance tools. All grouped up, ready to use without running app through IDE."
version: 0.0.4
homepage: https://github.com/RelappsStudio/cool_devtool
repository: https://github.com/RelappsStudio/cool_devtool.git
issue_tracker: https://github.com/RelappsStudio/cool_devtool/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
